POST https://junctionx-bp-22.apisc.host/api/user/create HTTP/1.1
Content-type: application/json

{
  "country": "hu"
}

###
POST http://localhost:8080/user/setTarget/fr/e9141004-a6b2-4665-ac96-b535de71b224  HTTP/1.1

###
GET https://junctionx-bp-22.apisc.host/api/user/ccf9759d-f26a-4d9b-b301-debe121ae509 HTTP/1.1



###
GET https://junctionx-bp-22.apisc.host/api/transaction/transactions/8b8a6ca1-63fa-4dab-8f5f-60c1f5d7a5ca HTTP/1.1

###
GET http://localhost:8080/transaction/summary/175d95e6-a1eb-414d-b5cb-0d8809bdd603 HTTP/1.1

###
POST http://localhost:8080/transaction HTTP/1.1
Content-type: application/json

{
  "amount": 10,
  "userId": "e9141004-a6b2-4665-ac96-b535de71b224",
  "category": "food"
}

###
GET https://junctionx-bp-22.apisc.host/api/countries