POST https://travelwise.apisc.host/api/user/create HTTP/1.1
Content-type: application/json

{
  "country": "hu"
}

###
POST http://localhost:8080/user/setTarget/fr/e9141004-a6b2-4665-ac96-b535de71b224  HTTP/1.1

###
GET https://travelwise.apisc.host/api/user/0c36adfe-64bb-4b90-8548-e2f008477c40 HTTP/1.1



###
GET https://travelwise.apisc.host/api/transaction/transactions/0c36adfe-64bb-4b90-8548-e2f008477c40 HTTP/1.1

###
GET http://localhost:8080/transaction/summary/175d95e6-a1eb-414d-b5cb-0d8809bdd603 HTTP/1.1

###
POST http://localhost:8080/transaction HTTP/1.1
Content-type: application/json

{
  "amount": 10,
  "userId": "e9141004-a6b2-4665-ac96-b535de71b224",
  "category": "food"
}

###
GET https://junctionx-bp-22.apisc.host/api/countries