deployment:
  name: junctionx-bp-22
  repository: localhost:32000
  imagePullPolicy: IfNotPresent

ingress:
  host: junctionx-bp-22.apisc.host

api:
  name: api
  image: junctionx-bp-22/api
  tag: latest
  replicas: 1
  port: 8080
  resources: {}


