deployment:
  name: junctionx-bp-22
  repository: localhost:32000
  imagePullPolicy: Always

ingress:
  host: travelwise.apisc.host

api:
  name: api
  image: junctionx-bp-22/api
  tag: latest
  replicas: 1
  port: 8080
  resources: {}

app:
  name: app
  image: junctionx-bp-22/app
  tag: latest
  replicas: 1
  port: 8080
  resources: {}

file:
  name: file
  image: junctionx-bp-22/file
  tag: latest
  replicas: 1
  port: 8080
  location: /home/azureuser/service/junctionx-bp-22-files
  resources: {}
