apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-{{ .Values.api.name }}-deployment
  labels:
    app: {{ .Values.deployment.name }}-{{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}-{{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}-{{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.repository }}/{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          env:
            - name: DATABASE_HOST
              value: {{.Values.db.host }}
            - name: DATABASE_DATABASE
              value: {{.Values.db.database }}
            - name: DATABASE_USER
              value: {{.Values.db.user }}
            - name: DATABASE_PASSWORD
              value: {{.Values.db.password }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
