apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-{{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.deployment.name }}-{{ .Values.app.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.app.port }}
